# @package _global_.model

# Model type identifier
type: lstm

# Model architecture parameters
in_channels: 5         
out_channels: 2       
hidden_channels: [32, 64, 128]   
kernel_size: 5            
num_layers: 3              